Database:
  #SQLite is the default database, it is recommended to use an SQL but SQLite works in place of one.
  SQLite: true
  #If SQLite is true this does not matter.
  SQL:
    Host: "local_host"
    Port: "port"
    Database: "db"
    User: "root"
    Password: "toor"